-----------------------------------------------------------------------------
-- HYPERSONIC SQL SCRIPT FOR ACEGI DNS
-----------------------------------------------------------------------------
-- 
-- We've use the SOA and RR schema adopted by the myDns application, with
-- the following changes:
--
--   * The "int4" data types have been replaced with "integer"
--   * The SOA.ID is no longer an identity column
--   * The SOA.ID now has a FK to DOMAIN.ID with a CASCADE DELETE
-- 
-- The net effect of these changes are that the DOMAIN.ID is the only auto
-- identity column and the value assigned to the DOMAIN.ID is shared with
-- all children SOA.ID and RR.ZONE colums.
-- 
-- $Id$
-----------------------------------------------------------------------------

drop table acl_permission;
drop table acl_object_identity;
drop table rr;
drop table soa;
drop table domain;

create table acl_object_identity (
  id integer generated by default as identity not null primary key,
  object_identity varchar(250) not null,
  parent_object integer,
  acl_class varchar(250) not null,
  unique (object_identity),
  foreign key (parent_object) references acl_object_identity (id) on delete cascade
);

create table acl_permission (
  id integer generated by default as identity not null primary key,
  acl_object_identity integer not null,
  recipient varchar(100) not null,
  mask integer not null,
  unique (acl_object_identity,recipient),
  foreign key (acl_object_identity) references acl_object_identity (id) on delete cascade
);

create table domain (
   id integer generated by default as identity not null primary key,
   parent_domain_id integer,
   full_name varchar(63) not null,
   foreign key (parent_domain_id) references domain (id) on delete cascade,
   unique(full_name)
);

create table soa (
   id integer not null primary key,
   origin varchar(255) not null,
   ns varchar(255) not null,
   mbox varchar(255) not null,
   serial integer default 1 not null,
   refresh integer default 28800 not null,
   retry integer default 7200 not null,
   expire integer default 604800 not null,
   minimum integer default 86400 not null,
   ttl integer default 86400 not null,
   foreign key (id) references domain (id) on delete cascade,
   unique (origin)
);

create table rr (
   id integer generated by default as identity not null primary key,
   zone integer not null,
   name varchar(64) not null,
   type varchar(5) not null, 
   data varchar(128) not null,
   aux integer default 0 not null,
   ttl integer default 86400 not null,
   unique (zone,name,type,data),
   foreign key (zone) references soa (id) on delete cascade,
   check
       (type='A' or type='AAAA'
       or type='ALIAS'
       or type='CNAME' or type='HINFO' or type='MX' or type='NS'
       or type='PTR' or type='RP' or type='SRV' or type='TXT')
);

insert into domain (id, parent_domain_id, full_name) values (1, null, 'com.au.');
insert into domain (id, parent_domain_id, full_name) values (2, 1, 'acegi.com.au.');
insert into domain (id, parent_domain_id, full_name) values (3, 1, 'eopal.com.au.');

-- ID must match the DOMAIN table
insert into soa(id, origin, ns, mbox) values (2, 'acegi.com.au.', 'ns1.acegi.com.au.', 'mbox.acegi.com.au.');
insert into soa(id, origin, ns, mbox) values (3, 'eopal.com.au.', 'ns1.acegi.com.au.', 'mbox.acegi.com.au.');

-- ZONE must match the SOA (=DOMAIN) table
insert into rr (id, zone, name, type, data) values (null, 2, 'www', 'A', '192.168.0.1');
insert into rr (id, zone, name, type, data) values (null, 3, 'www', 'A', '192.168.0.100');
